In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from warnings import filterwarnings
filterwarnings('ignore')

In [ ]:
matches = pd.read_csv('/content/IPL_Matches_2008_2022.csv')
matches.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [ ]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int64
 1   City             899 non-null    object
 2   Date             950 non-null    object
 3   Season           950 non-null    object
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    object
 6   Team2            950 non-null    object
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    object
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    object
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: float64(1), int64(1), object(18)
memory usage: 148.6+ KB

In [ ]:
#working on column 'city'
matches[matches['City'].isnull()]

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
134,1237181,NaN,2020-11-10,2020/21,Final,Delhi Capitals,Mumbai Indians,Dubai International Cricket Stadium,Delhi Capitals,bat,N,Mumbai Indians,Wickets,5.0,NaN,TA Boult,"['MP Stoinis', 'S Dhawan', 'AM Rahane', 'SS Iy...","['RG Sharma', 'Q de Kock', 'SA Yadav', 'Ishan ...",CB Gaffaney,Nitin Menon
137,1237177,NaN,2020-11-05,2020/21,Qualifier 1,Mumbai Indians,Delhi Capitals,Dubai International Cricket Stadium,Delhi Capitals,field,N,Mumbai Indians,Runs,57.0,NaN,JJ Bumrah,"['Q de Kock', 'RG Sharma', 'SA Yadav', 'Ishan ...","['PP Shaw', 'S Dhawan', 'AM Rahane', 'SS Iyer'...",CB Gaffaney,Nitin Menon
138,1216495,NaN,2020-11-03,2020/21,56,Mumbai Indians,Sunrisers Hyderabad,Sharjah Cricket Stadium,Sunrisers Hyderabad,field,N,Sunrisers Hyderabad,Wickets,10.0,NaN,S Nadeem,"['RG Sharma', 'Q de Kock', 'SA Yadav', 'Ishan ...","['DA Warner', 'WP Saha', 'MK Pandey', 'KS Will...",C Shamshuddin,RK Illingworth
140,1216530,NaN,2020-11-01,2020/21,54,Kolkata Knight Riders,Rajasthan Royals,Dubai International Cricket Stadium,Rajasthan Royals,field,N,Kolkata Knight Riders,Runs,60.0,NaN,PJ Cummins,"['Shubman Gill', 'N Rana', 'RA Tripathi', 'SP ...","['RV Uthappa', 'BA Stokes', 'SPD Smith', 'SV S...",Nitin Menon,PR Reiffel
142,1216535,NaN,2020-10-31,2020/21,51,Delhi Capitals,Mumbai Indians,Dubai International Cricket Stadium,Mumbai Indians,field,N,Mumbai Indians,Wickets,9.0,NaN,Ishan Kishan,"['PP Shaw', 'S Dhawan', 'SS Iyer', 'RR Pant', ...","['Ishan Kishan', 'Q de Kock', 'SA Yadav', 'SS ...",YC Barde,PR Reiffel
143,1216502,NaN,2020-10-31,2020/21,52,Royal Challengers Bangalore,Sunrisers Hyderabad,Sharjah Cricket Stadium,Sunrisers Hyderabad,field,N,Sunrisers Hyderabad,Wickets,5.0,NaN,Sandeep Sharma,"['JR Philippe', 'D Padikkal', 'V Kohli', 'AB d...","['DA Warner', 'WP Saha', 'MK Pandey', 'KS Will...",KN Ananthapadmanabhan,K Srinivasan
145,1216536,NaN,2020-10-29,2020/21,49,Kolkata Knight Riders,Chennai Super Kings,Dubai International Cricket Stadium,Chennai Super Kings,field,N,Chennai Super Kings,Wickets,6.0,NaN,RD Gaikwad,"['Shubman Gill', 'N Rana', 'SP Narine', 'RK Si...","['SR Watson', 'RD Gaikwad', 'AT Rayudu', 'MS D...",C Shamshuddin,RK Illingworth
147,1216524,NaN,2020-10-27,2020/21,47,Sunrisers Hyderabad,Delhi Capitals,Dubai International Cricket Stadium,Delhi Capitals,field,N,Sunrisers Hyderabad,Runs,88.0,NaN,WP Saha,"['DA Warner', 'WP Saha', 'MK Pandey', 'KS Will...","['AM Rahane', 'S Dhawan', 'MP Stoinis', 'SO He...",AK Chaudhary,Nitin Menon
148,1216520,NaN,2020-10-26,2020/21,46,Kolkata Knight Riders,Kings XI Punjab,Sharjah Cricket Stadium,Kings XI Punjab,field,N,Kings XI Punjab,Wickets,8.0,NaN,CH Gayle,"['Shubman Gill', 'N Rana', 'RA Tripathi', 'KD ...","['KL Rahul', 'Mandeep Singh', 'CH Gayle', 'N P...",KN Ananthapadmanabhan,RK Illingworth
150,1216544,NaN,2020-10-25,2020/21,44,Royal Challengers Bangalore,Chennai Super Kings,Dubai International Cricket Stadium,Royal Challengers Bangalore,bat,N,Chennai Super Kings,Wickets,8.0,NaN,RD Gaikwad,"['D Padikkal', 'AJ Finch', 'V Kohli', 'AB de V...","['RD Gaikwad', 'F du Plessis', 'AT Rayudu', 'M...",C Shamshuddin,RK Illingworth
151,1216498,NaN,2020-10-24,2020/21,43,Kings XI Punjab,Sunrisers Hyderabad,Dubai International Cricket Stadium,Sunrisers Hyderabad,field,N,Kings XI Punjab,Runs,12.0,NaN,CJ Jordan,"['KL Rahul', 'Mandeep Singh', 'CH Gayle', 'N P...","['DA Warner', 'JM Bairstow', 'MK Pandey', 'Abd...",AY Dandekar,PR Reiffel
153,1216521,NaN,2020-10-23,2020/21,41,Chennai Super Kings,Mumbai Indians,Sharjah Cricket Stadium,Mumbai Indians,field,N,Mumbai Indians,Wickets,10.0,NaN,TA Boult,"['RD Gaikwad', 'F du Plessis', 'AT Rayudu', 'N...","['Q de Kock', 'Ishan Kishan', 'SA Yadav', 'SS ...",C Shamshuddin,VA Kulkarni
154,1216518,NaN,2020-10-22,2020/21,40,Rajasthan Royals,Sunrisers Hyderabad,Dubai International Cricket Stadium,Sunrisers Hyderabad,field,N,Sunrisers Hyderabad,Wickets,8.0,NaN,MK Pandey,"['RV Uthappa', 'BA Stokes', 'SV Samson', 'JC B...","['DA Warner', 'JM Bairstow', 'MK Pandey', 'V S...",Nitin Menon,PR Reiffel
156,1216546,NaN,2020-10-20,2020/21,38,Delhi Capitals,Kings XI Punjab,Dubai International Cricket Stadium,Delhi Capitals,bat,N,Kings XI Punjab,Wickets,5.0,NaN,S Dhawan,"['PP Shaw', 'S Dhawan', 'SS Iyer', 'RR Pant', ...","['KL Rahul', 'MA Agarwal', 'CH Gayle', 'N Poor...",C Shamshuddin,RK Illingworth
159,1216517,NaN,2020-10-18,2020/21,36,Mumbai Indians,Kings XI Punjab,Dubai International Cricket Stadium,Mumbai Indians,bat,Y,Kings XI Punjab,SuperOver,NaN,NaN,KL Rahul,"['RG Sharma', 'Q de Kock', 'SA Yadav', 'Ishan ...","['KL Rahul', 'MA Agarwal', 'CH Gayle', 'N Poor...",Nitin Menon,PR Reiffel
160,1216522,NaN,2020-10-17,2020/21,33,Rajasthan Royals,Royal Challengers Bangalore,Dubai International Cricket Stadium,Rajasthan Royals,bat,N,Royal Challengers Bangalore,Wickets,7.0,NaN,AB de Villiers,"['RV Uthappa', 'BA Stokes', 'SV Samson', 'SPD ...","['D Padikkal', 'AJ Finch', 'V Kohli', 'AB de V...",AK Chaudhary,Nitin Menon
161,1216509,NaN,2020-10-17,2020/21,34,Chennai Super Kings,Delhi Capitals,Sharjah Cricket Stadium,Chennai Super Kings,bat,N,Delhi Capitals,Wickets,5.0,NaN,S Dhawan,"['SM Curran', 'F du Plessis', 'SR Watson', 'AT...","['PP Shaw', 'S Dhawan', 'AM Rahane', 'SS Iyer'...",KN Ananthapadmanabhan,RK Illingworth
163,1216531,NaN,2020-10-15,2020/21,31,Royal Challengers Bangalore,Kings XI Punjab,Sharjah Cricket Stadium,Royal Challengers Bangalore,bat,N,Kings XI Punjab,Wickets,8.0,NaN,KL Rahul,"['AJ Finch', 'D Padikkal', 'V Kohli', 'Washing...","['KL Rahul', 'MA Agarwal', 'CH Gayle', 'N Poor...",KN Ananthapadmanabhan,C Shamshuddin
164,1216543,NaN,2020-10-14,2020/21,30,Delhi Capitals,Rajasthan Royals,Dubai International Cricket Stadium,Delhi Capitals,bat,N,Delhi Capitals,Runs,13.0,NaN,A Nortje,"['PP Shaw', 'S Dhawan', 'AM Rahane', 'SS Iyer'...","['BA Stokes', 'JC Buttler', 'SPD Smith', 'SV S...",AK Chaudhary,Nitin Menon
165,1216528,NaN,2020-10-13,2020/21,29,Chennai Super Kings,Sunrisers Hyderabad,Dubai International Cricket Stadium,Chennai Super Kings,bat,N,Chennai Super Kings,Runs,20.0,NaN,RA Jadeja,"['SM Curran', 'F du Plessis', 'SR Watson', 'AT...","['DA Warner', 'JM Bairstow', 'MK Pandey', 'KS ...",AK Chaudhary,PR Reiffel
166,1216540,NaN,2020-10-12,2020/21,28,Royal Challengers Bangalore,Kolkata Knight Riders,Sharjah Cricket Stadium,Royal Challengers Bangalore,bat,N,Royal Challengers Bangalore,Runs,82.0,NaN,AB de Villiers,"['AJ Finch', 'D Padikkal', 'V Kohli', 'AB de V...","['T Banton', 'Shubman Gill', 'N Rana', 'EJG Mo...",RK Illingworth,K Srinivasan
167,1216507,NaN,2020-10-11,2020/21,26,Sunrisers Hyderabad,Rajasthan Royals,Dubai International Cricket Stadium,Sunrisers Hyderabad,bat,N,Rajasthan Royals,Wickets,5.0,NaN,R Tewatia,"['DA Warner', 'JM Bairstow', 'MK Pandey', 'KS ...","['BA Stokes', 'JC Buttler', 'SPD Smith', 'SV S...",YC Barde,PR Reiffel
170,1216525,NaN,2020-10-10,2020/21,25,Royal Challengers Bangalore,Chennai Super Kings,Dubai International Cricket Stadium,Royal Challengers Bangalore,bat,N,Royal Challengers Bangalore,Runs,37.0,NaN,V Kohli,"['D Padikkal', 'AJ Finch', 'V Kohli', 'AB de V...","['SR Watson', 'F du Plessis', 'AT Rayudu', 'N ...",AK Chaudhary,PR Reiffel
171,1216500,NaN,2020-10-09,2020/21,23,Delhi Capitals,Rajasthan Royals,Sharjah Cricket Stadium,Rajasthan Royals,field,N,Delhi Capitals,Runs,46.0,NaN,R Ashwin,"['PP Shaw', 'S Dhawan', 'SS Iyer', 'RR Pant', ...","['YBK Jaiswal', 'JC Buttler', 'SPD Smith', 'SV...",KN Ananthapadmanabhan,C Shamshuddin
172,1216542,NaN,2020-10-08,2020/21,22,Sunrisers Hyderabad,Kings XI Punjab,Dubai International Cricket Stadium,Sunrisers Hyderabad,bat,N,Sunrisers Hyderabad,Runs,69.0,NaN,JM Bairstow,"['DA Warner', 'JM Bairstow', 'Abdul Samad', 'M...","['KL Rahul', 'MA Agarwal', 'P Simran Singh', '...",AK Chaudhary,Nitin Menon
175,1216519,NaN,2020-10-05,2020/21,19,Delhi Capitals,Royal Challengers Bangalore,Dubai International Cricket Stadium,Royal Challengers Bangalore,field,N,Delhi Capitals,Runs,59.0,NaN,AR Patel,"['PP Shaw', 'S Dhawan', 'SS Iyer', 'RR Pant', ...","['D Padikkal', 'AJ Finch', 'V Kohli', 'AB de V...",Nitin Menon,YC Barde
176,1216513,NaN,2020-10-04,2020/21,18,Kings XI Punjab,Chennai Super Kings,Dubai International Cricket Stadium,Kings XI Punjab,bat,N,Chennai Super Kings,Wickets,10.0,NaN,SR Watson,"['KL Rahul', 'MA Agarwal', 'Mandeep Singh', 'N...","['SR Watson', 'F du Plessis', 'AT Rayudu', 'KM...",AY Dandekar,Nitin Menon
177,1216538,NaN,2020-10-04,2020/21,17,Mumbai Indians,Sunrisers Hyderabad,Sharjah Cricket Stadium,Mumbai Indians,bat,N,Mumbai Indians,Runs,34.0,NaN,TA Boult,"['RG Sharma', 'Q de Kock', 'SA Yadav', 'Ishan ...","['DA Warner', 'JM Bairstow', 'MK Pandey', 'KS ...",KN Ananthapadmanabhan,RK Illingworth
179,1216515,NaN,2020-10-03,2020/21,16,Delhi Capitals,Kolkata Knight Riders,Sharjah Cricket Stadium,Kolkata Knight Riders,field,N,Delhi Capitals,Runs,18.0,NaN,SS Iyer,"['PP Shaw', 'S Dhawan', 'SS Iyer', 'RR Pant', ...","['Shubman Gill', 'SP Narine', 'N Rana', 'AD Ru...",VA Kulkarni,RK Illingworth
180,1216516,NaN,2020-10-02,2020/21,14,Sunrisers Hyderabad,Chennai Super Kings,Dubai International Cricket Stadium,Sunrisers Hyderabad,bat,N,Sunrisers Hyderabad,Runs,7.0,NaN,PK Garg,"['DA Warner', 'JM Bairstow', 'MK Pandey', 'KS ...","['F du Plessis', 'SR Watson', 'AT Rayudu', 'KM...",AK Chaudhary,PR Reiffel
182,1216504,NaN,2020-09-30,2020/21,12,Kolkata Knight Riders,Rajasthan Royals,Dubai International Cricket Stadium,Rajasthan Royals,field,N,Kolkata Knight Riders,Runs,37.0,NaN,Shivam Mavi,"['Shubman Gill', 'SP Narine', 'N Rana', 'AD Ru...","['JC Buttler', 'SPD Smith', 'SV Samson', 'RV U...",KN Ananthapadmanabhan,C Shamshuddin
184,1216547,NaN,2020-09-28,2020/21,10,Royal Challengers Bangalore,Mumbai Indians,Dubai International Cricket Stadium,Mumbai Indians,field,Y,Royal Challengers Bangalore,SuperOver,NaN,NaN,AB de Villiers,"['D Padikkal', 'AJ Finch', 'V Kohli', 'AB de V...","['RG Sharma', 'Q de Kock', 'SA Yadav', 'Ishan ...",Nitin Menon,PR Reiffel
185,1216527,NaN,2020-09-27,2020/21,9,Kings XI Punjab,Rajasthan Royals,Sharjah Cricket Stadium,Rajasthan Royals,field,N,Rajasthan Royals,Wickets,4.0,NaN,SV Samson,"['KL Rahul', 'MA Agarwal', 'GJ Maxwell', 'N Po...","['JC Buttler', 'SPD Smith', 'SV Samson', 'R Te...",RK Illingworth,K Srinivasan
187,1216539,NaN,2020-09-25,2020/21,7,Delhi Capitals,Chennai Super Kings,Dubai International Cricket Stadium,Chennai Super Kings,field,N,Delhi Capitals,Runs,44.0,NaN,PP Shaw,"['PP Shaw', 'S Dhawan', 'RR Pant', 'SS Iyer', ...","['M Vijay', 'SR Watson', 'F du Plessis', 'RD G...",KN Ananthapadmanabhan,RK Illingworth
188,1216510,NaN,2020-09-24,2020/21,6,Kings XI Punjab,Royal Challengers Bangalore,Dubai International Cricket Stadium,Royal Challengers Bangalore,field,N,Kings XI Punjab,Runs,97.0,NaN,KL Rahul,"['KL Rahul', 'MA Agarwal', 'N Pooran', 'GJ Max...","['D Padikkal', 'AJ Finch', 'JR Philippe', 'V K...",AK Chaudhary,PR Reiffel
190,1216496,NaN,2020-09-22,2020/21,4,Rajasthan Royals,Chennai Super Kings,Sharjah Cricket Stadium,Chennai Super Kings,field,N,Rajasthan Royals,Runs,16.0,NaN,SV Samson,"['YBK Jaiswal', 'SPD Smith', 'SV Samson', 'DA ...","['M Vijay', 'SR Watson', 'F du Plessis', 'SM C...",C Shamshuddin,VA Kulkarni
191,1216534,NaN,2020-09-21,2020/21,3,Royal Challengers Bangalore,Sunrisers Hyderabad,Dubai International Cricket Stadium,Sunrisers Hyderabad,field,N,Royal Challengers Bangalore,Runs,10.0,NaN,YS Chahal,"['D Padikkal', 'AJ Finch', 'V Kohli', 'AB de V...","['DA Warner', 'JM Bairstow', 'MK Pandey', 'PK ...",AY Dandekar,Nitin Menon
192,1216493,NaN,2020-09-20,2020/21,2,Delhi Capitals,Kings XI Punjab,Dubai International Cricket Stadium,Kings XI Punjab,field,Y,Delhi Capitals,SuperOver,NaN,NaN,MP Stoinis,"['PP Shaw', 'S Dhawan', 'SO Hetmyer', 'SS Iyer...","['KL Rahul', 'MA Agarwal', 'KK Nair', 'N Poora...",AK Chaudhary,Nitin Menon
532,729317,NaN,2014-04-30,2014,20,Mumbai Indians,Sunrisers Hyderabad,Dubai International Cricket Stadium,Mumbai Indians,field,N,Sunrisers Hyderabad,Runs,15.0,NaN,B Kumar,"['BR Dunk', 'RG Sharma', 'CJ Anderson', 'AT Ra...","['AJ Finch', 'S Dhawan', 'KL Rahul', 'DA Warne...",HDPK Dharmasena,M Erasmus
534,729313,NaN,2014-04-28,2014,18,Kings XI Punjab,Royal Challengers Bangalore,Dubai International Cricket Stadium,Kings XI Punjab,field,N,Kings XI Punjab,Wickets,5.0,NaN,Sandeep Sharma,"['CA Pujara', 'V Sehwag', 'WP Saha', 'GJ Maxwe...","['CH Gayle', 'PA Patel', 'V Kohli', 'YV Takawa...",BF Bowden,S Ravi
535,729311,NaN,2014-04-27,2014,17,Sunrisers Hyderabad,Chennai Super Kings,Sharjah Cricket Stadium,Sunrisers Hyderabad,bat,N,Chennai Super Kings,Wickets,5.0,NaN,DR Smith,"['AJ Finch', 'S Dhawan', 'DA Warner', 'KL Rahu...","['DR Smith', 'BB McCullum', 'SK Raina', 'MS Dh...",AK Chaudhary,VA Kulkarni
536,729309,NaN,2014-04-27,2014,16,Delhi Daredevils,Mumbai Indians,Sharjah Cricket Stadium,Mumbai Indians,bat,N,Delhi Daredevils,Wickets,6.0,NaN,M Vijay,"['Q de Kock', 'M Vijay', 'JP Duminy', 'KP Piet...","['RG Sharma', 'AP Tare', 'CJ Anderson', 'AT Ra...",Aleem Dar,VA Kulkarni
539,729301,NaN,2014-04-25,2014,12,Sunrisers Hyderabad,Delhi Daredevils,Dubai International Cricket Stadium,Sunrisers Hyderabad,bat,N,Sunrisers Hyderabad,Runs,4.0,NaN,AJ Finch,"['S Dhawan', 'AJ Finch', 'DA Warner', 'KL Rahu...","['Q de Kock', 'M Vijay', 'KP Pietersen', 'KD K...",M Erasmus,S Ravi
540,729303,NaN,2014-04-25,2014,13,Chennai Super Kings,Mumbai Indians,Dubai International Cricket Stadium,Mumbai Indians,bat,N,Chennai Super Kings,Wickets,7.0,NaN,MM Sharma,"['DR Smith', 'BB McCullum', 'SK Raina', 'F du ...","['MEK Hussey', 'AP Tare', 'CJ Anderson', 'RG S...",BF Bowden,M Erasmus
541,729299,NaN,2014-04-24,2014,11,Royal Challengers Bangalore,Kolkata Knight Riders,Sharjah Cricket Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,2.0,NaN,CA Lynn,"['PA Patel', 'YV Takawale', 'V Kohli', 'Yuvraj...","['JH Kallis', 'G Gambhir', 'MK Pandey', 'CA Ly...",Aleem Dar,VA Kulkarni
542,729297,NaN,2014-04-23,2014,10,Rajasthan Royals,Chennai Super Kings,Dubai International Cricket Stadium,Rajasthan Royals,field,N,Chennai Super Kings,Runs,7.0,NaN,RA Jadeja,"['AM Nayar', 'AM Rahane', 'SV Samson', 'SR Wat...","['DR Smith', 'BB McCullum', 'SK Raina', 'F du ...",HDPK Dharmasena,RK Illingworth
543,729295,NaN,2014-04-22,2014,9,Kings XI Punjab,Sunrisers Hyderabad,Sharjah Cricket Stadium,Sunrisers Hyderabad,field,N,Kings XI Punjab,Runs,72.0,NaN,GJ Maxwell,"['CA Pujara', 'V Sehwag', 'GJ Maxwell', 'DA Mi...","['AJ Finch', 'S Dhawan', 'DA Warner', 'KL Rahu...",M Erasmus,S Ravi
545,729291,NaN,2014-04-20,2014,7,Rajasthan Royals,Kings XI Punjab,Sharjah Cricket Stadium,Kings XI Punjab,field,N,Kings XI Punjab,Wickets,7.0,NaN,GJ Maxwell,"['AM Nayar', 'AM Rahane', 'SV Samson', 'SR Wat...","['CA Pujara', 'V Sehwag', 'WP Saha', 'GJ Maxwe...",BF Bowden,M Erasmus
546,729289,NaN,2014-04-19,2014,6,Kolkata Knight Riders,Delhi Daredevils,Dubai International Cricket Stadium,Kolkata Knight Riders,bat,N,Delhi Daredevils,Wickets,4.0,NaN,JP Duminy,"['JH Kallis', 'G Gambhir', 'MK Pandey', 'RV Ut...","['M Vijay', 'MA Agarwal', 'KD Karthik', 'LRPL ...",Aleem Dar,VA Kulkarni
547,729287,NaN,2014-04-19,2014,5,Royal Challengers Bangalore,Mumbai Indians,Dubai International Cricket Stadium,Royal Challengers Bangalore,field,N,Royal Challengers Bangalore,Wickets,7.0,NaN,PA Patel,"['NJ Maddinson', 'PA Patel', 'V Kohli', 'Yuvra...","['MEK Hussey', 'AP Tare', 'AT Rayudu', 'RG Sha...",Aleem Dar,AK Chaudhary
550,729281,NaN,2014-04-17,2014,2,Delhi Daredevils,Royal Challengers Bangalore,Sharjah Cricket Stadium,Royal Challengers Bangalore,field,N,Royal Challengers Bangalore,Wickets,8.0,NaN,YS Chahal,"['MA Agarwal', 'M Vijay', 'KD Karthik', 'MK Ti...","['PA Patel', 'NJ Maddinson', 'V Kohli', 'Yuvra...",Aleem Dar,S Ravi

In [ ]:
for i in range(len(matches)):
    if (matches['Venue'] == 'Dubai International Cricket Stadium')[i] == True:
        matches['City'][i] = 'Dubai'
    elif (matches['Venue'] == 'Sharjah Cricket Stadium')[i] == True:
        matches['City'][i] = 'Sharjah'
    else:
        matches['City'][i] = matches['City'][i]

In [ ]:
matches['City'].isnull().sum()

0

In [ ]:
# checking filled values:
matches[(matches['ID'] == 1216495) | (matches['ID'] == 1216530)]

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
138,1216495,Sharjah,2020-11-03,2020/21,56,Mumbai Indians,Sunrisers Hyderabad,Sharjah Cricket Stadium,Sunrisers Hyderabad,field,N,Sunrisers Hyderabad,Wickets,10.0,NaN,S Nadeem,"['RG Sharma', 'Q de Kock', 'SA Yadav', 'Ishan ...","['DA Warner', 'WP Saha', 'MK Pandey', 'KS Will...",C Shamshuddin,RK Illingworth
140,1216530,Dubai,2020-11-01,2020/21,54,Kolkata Knight Riders,Rajasthan Royals,Dubai International Cricket Stadium,Rajasthan Royals,field,N,Kolkata Knight Riders,Runs,60.0,NaN,PJ Cummins,"['Shubman Gill', 'N Rana', 'RA Tripathi', 'SP ...","['RV Uthappa', 'BA Stokes', 'SPD Smith', 'SV S...",Nitin Menon,PR Reiffel

In [ ]:
#importing deliveries data:
delivery = pd.read_csv('/content/IPL_Ball_by_Ball_2008_2022.csv',error_bad_lines=False)
delivery.head()

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals

In [ ]:
# calculating total runs after each inning:
temp_df = delivery.groupby(['ID','innings'])['total_run'].sum().reset_index()

In [ ]:
temp_df

           ID  innings  total_run
0      335982        1        222
1      335982        2         82
2      335983        1        240
3      335983        2        207
4      335984        1        129
...       ...      ...        ...
1923  1312198        2        193
1924  1312199        1        157
1925  1312199        2        161
1926  1312200        1        130
1927  1312200        2        133

[1928 rows x 3 columns]

In [ ]:
#we only need 1st inning score for further calculations:
temp_df = temp_df[temp_df['innings'] == 1]

In [ ]:
#merging temp_df with matches df:
match_df = matches.merge(temp_df,on='ID')

In [ ]:
match_df.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,...,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,innings,total_run
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,...,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,1,130
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,...,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon,1,157
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,...,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough,1,207
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,...,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma,1,188
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,...,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan,1,157

In [ ]:
#working on teams:
match_df['Team1'].unique()

array(['Rajasthan Royals', 'Royal Challengers Bangalore',
       'Sunrisers Hyderabad', 'Delhi Capitals', 'Chennai Super Kings',
       'Gujarat Titans', 'Lucknow Super Giants', 'Kolkata Knight Riders',
       'Punjab Kings', 'Mumbai Indians', 'Kings XI Punjab',
       'Delhi Daredevils', 'Rising Pune Supergiant', 'Gujarat Lions',
       'Rising Pune Supergiants', 'Pune Warriors', 'Deccan Chargers',
       'Kochi Tuskers Kerala'], dtype=object)

In [ ]:
#re-nameing same teams:

#'Delhi Daredevils' --> 'Delhi Capitals':
match_df['Team1'] = match_df['Team1'].str.replace('Delhi Daredevils','Delhi Capitals')
match_df['Team2'] = match_df['Team2'].str.replace('Delhi Daredevils','Delhi Capitals')

#'Deccan Chargers' --> 'Sunrisers Hyderabad':
match_df['Team1'] = match_df['Team1'].str.replace('Deccan Chargers','Sunrisers Hyderabad')
match_df['Team2'] = match_df['Team2'].str.replace('Deccan Chargers','Sunrisers Hyderabad')

#'Gujarat Lions' --> 'Gujarat Titans'
match_df['Team1'] = match_df['Team1'].str.replace('Gujarat Lions','Gujarat Titans')
match_df['Team2'] = match_df['Team2'].str.replace('Gujarat Lions','Gujarat Titans')

In [ ]:
#keeping only those teams who played till 2022:
teams = ['Royal Challengers Bangalore', 'Kings XI Punjab',
       'Delhi Capitals', 'Mumbai Indians', 'Kolkata Knight Riders',
       'Rajasthan Royals','Chennai Super Kings','Sunrisers Hyderabad','Gujarat Titans'
        ,'Lucknow Super Giants']

match_df = match_df[match_df['Team1'].isin(teams)]
match_df = match_df[match_df['Team2'].isin(teams)]

In [ ]:
match_df['Team1'].unique()

array(['Rajasthan Royals', 'Royal Challengers Bangalore',
       'Delhi Capitals', 'Chennai Super Kings', 'Gujarat Titans',
       'Lucknow Super Giants', 'Sunrisers Hyderabad',
       'Kolkata Knight Riders', 'Mumbai Indians', 'Kings XI Punjab'],
      dtype=object)

'''
required cols for our final_df to predict the result would be:

('batting_team',
'bowling_team',
'city',
'current_score',
'overs_completed',
'wickets_left',
'crr',
'runs_in_last_3,
'total_runs',
)
'''

In [ ]:
match_df = match_df[['ID','City','Team1','Team2','total_run']]

In [ ]:
match_df.head()

,ID,City,Team1,Team2,total_run
0,1312200,Ahmedabad,Rajasthan Royals,Gujarat Titans,130
1,1312199,Ahmedabad,Royal Challengers Bangalore,Rajasthan Royals,157
2,1312198,Kolkata,Royal Challengers Bangalore,Lucknow Super Giants,207
3,1312197,Kolkata,Rajasthan Royals,Gujarat Titans,188
5,1304115,Mumbai,Delhi Capitals,Mumbai Indians,159

In [ ]:
#merging match_df with delivery to get ball by ball details:
delivery_df = delivery.merge(match_df,on='ID')

In [ ]:
#keeping values where inning = 1 to predict scored for 1st innings:
delivery_df = delivery_df[delivery_df['innings'] == 1]

In [ ]:
delivery_df.head()

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,...,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,City,Team1,Team2,total_run_y
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,...,0,0,NaN,NaN,NaN,Rajasthan Royals,Ahmedabad,Rajasthan Royals,Gujarat Titans,130
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,...,0,0,NaN,NaN,NaN,Rajasthan Royals,Ahmedabad,Rajasthan Royals,Gujarat Titans,130
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,...,0,0,NaN,NaN,NaN,Rajasthan Royals,Ahmedabad,Rajasthan Royals,Gujarat Titans,130
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,...,0,0,NaN,NaN,NaN,Rajasthan Royals,Ahmedabad,Rajasthan Royals,Gujarat Titans,130
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,...,0,0,NaN,NaN,NaN,Rajasthan Royals,Ahmedabad,Rajasthan Royals,Gujarat Titans,130

In [ ]:
#calculating the current score after every ball:
delivery_df['current_score'] = delivery_df.groupby('ID')['total_run_x'].cumsum()

In [ ]:
#calculating wickets left after every ball:
delivery_df['wickets_left'] = 10 - (delivery_df.groupby('ID')['isWicketDelivery'].cumsum())

In [ ]:
#calculating balls left after every ball:
delivery_df['balls_left'] = 120 - (delivery_df['overs']*6 + delivery_df['ballnumber'])

In [ ]:
delivery_df

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,...,kind,fielders_involved,BattingTeam,City,Team1,Team2,total_run_y,current_score,wickets_left,balls_left
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,...,NaN,NaN,Rajasthan Royals,Ahmedabad,Rajasthan Royals,Gujarat Titans,130,0,10,119
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,...,NaN,NaN,Rajasthan Royals,Ahmedabad,Rajasthan Royals,Gujarat Titans,130,1,10,118
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,...,NaN,NaN,Rajasthan Royals,Ahmedabad,Rajasthan Royals,Gujarat Titans,130,2,10,117
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,...,NaN,NaN,Rajasthan Royals,Ahmedabad,Rajasthan Royals,Gujarat Titans,130,2,10,116
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,...,NaN,NaN,Rajasthan Royals,Ahmedabad,Rajasthan Royals,Gujarat Titans,130,2,10,115
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198295,335982,1,19,2,BB McCullum,P Kumar,Mohammad Hafeez,NaN,6,0,...,NaN,NaN,Kolkata Knight Riders,Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,222,212,7,4
198296,335982,1,19,3,BB McCullum,P Kumar,Mohammad Hafeez,NaN,2,0,...,NaN,NaN,Kolkata Knight Riders,Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,222,214,7,3
198297,335982,1,19,4,BB McCullum,P Kumar,Mohammad Hafeez,NaN,0,0,...,NaN,NaN,Kolkata Knight Riders,Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,222,214,7,2
198298,335982,1,19,5,BB McCullum,P Kumar,Mohammad Hafeez,NaN,2,0,...,NaN,NaN,Kolkata Knight Riders,Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,222,216,7,1
198299,335982,1,19,6,BB McCullum,P Kumar,Mohammad Hafeez,NaN,6,0,...,NaN,NaN,Kolkata Knight Riders,Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,222,222,7,0

In [ ]:
#calculating current run rate(crr):
delivery_df['crr'] = (delivery_df['current_score']*6)/(120-delivery_df['balls_left'])

In [ ]:
#creating bowling team as there is no bowling team column in the df:

In [ ]:
def bowling_team(row):
    return row['Team1'] if row['Team2'] == row['BattingTeam'] else row['Team2']

In [ ]:
delivery_df['BowlingTeam'] = delivery_df.apply(bowling_team,axis=1)

In [ ]:
#checking the bowling column with other cols:
delivery_df[['Team1','Team2','BattingTeam','BowlingTeam']]

,Team1,Team2,BattingTeam,BowlingTeam
0,Rajasthan Royals,Gujarat Titans,Rajasthan Royals,Gujarat Titans
1,Rajasthan Royals,Gujarat Titans,Rajasthan Royals,Gujarat Titans
2,Rajasthan Royals,Gujarat Titans,Rajasthan Royals,Gujarat Titans
3,Rajasthan Royals,Gujarat Titans,Rajasthan Royals,Gujarat Titans
4,Rajasthan Royals,Gujarat Titans,Rajasthan Royals,Gujarat Titans
...,...,...,...,...
198295,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,Royal Challengers Bangalore
198296,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,Royal Challengers Bangalore
198297,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,Royal Challengers Bangalore
198298,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,Royal Challengers Bangalore
198299,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,Royal Challengers Bangalore

In [ ]:
#calculating runs scored in last 3 overs:
groups = delivery_df.groupby('ID')
ids = delivery_df['ID'].unique()
last_three = []

for id in ids:
    last_three.extend(groups.get_group(id).rolling(window=18).sum()['total_run_x'].values)

In [ ]:
delivery_df['last_three'] = last_three

In [ ]:
delivery_df

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,...,City,Team1,Team2,total_run_y,current_score,wickets_left,balls_left,crr,BowlingTeam,last_three
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,...,Ahmedabad,Rajasthan Royals,Gujarat Titans,130,0,10,119,0.000000,Gujarat Titans,NaN
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,...,Ahmedabad,Rajasthan Royals,Gujarat Titans,130,1,10,118,3.000000,Gujarat Titans,NaN
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,...,Ahmedabad,Rajasthan Royals,Gujarat Titans,130,2,10,117,4.000000,Gujarat Titans,NaN
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,...,Ahmedabad,Rajasthan Royals,Gujarat Titans,130,2,10,116,3.000000,Gujarat Titans,NaN
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,...,Ahmedabad,Rajasthan Royals,Gujarat Titans,130,2,10,115,2.400000,Gujarat Titans,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198295,335982,1,19,2,BB McCullum,P Kumar,Mohammad Hafeez,NaN,6,0,...,Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,222,212,7,4,10.965517,Royal Challengers Bangalore,51.0
198296,335982,1,19,3,BB McCullum,P Kumar,Mohammad Hafeez,NaN,2,0,...,Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,222,214,7,3,10.974359,Royal Challengers Bangalore,52.0
198297,335982,1,19,4,BB McCullum,P Kumar,Mohammad Hafeez,NaN,0,0,...,Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,222,214,7,2,10.881356,Royal Challengers Bangalore,46.0
198298,335982,1,19,5,BB McCullum,P Kumar,Mohammad Hafeez,NaN,2,0,...,Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,222,216,7,1,10.890756,Royal Challengers Bangalore,46.0
198299,335982,1,19,6,BB McCullum,P Kumar,Mohammad Hafeez,NaN,6,0,...,Bangalore,Royal Challengers Bangalore,Kolkata Knight Riders,222,222,7,0,11.100000,Royal Challengers Bangalore,50.0

In [ ]:
delivery_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 102524 entries, 0 to 198299
Data columns (total 27 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ID                 102524 non-null  int64
 1   innings            102524 non-null  int64
 2   overs              102524 non-null  int64
 3   ballnumber         102524 non-null  int64
 4   batter             102524 non-null  object
 5   bowler             102524 non-null  object
 6   non-striker        102524 non-null  object
 7   extra_type         5528 non-null    object
 8   batsman_run        102524 non-null  int64
 9   extras_run         102524 non-null  int64
 10  total_run_x        102524 non-null  int64
 11  non_boundary       102524 non-null  int64
 12  isWicketDelivery   102524 non-null  int64
 13  player_out         5043 non-null    object
 14  kind               5043 non-null    object
 15  fielders_involved  3657 non-null    object
 16  BattingTeam        102524 non-null  object
 17  City               102524 non-null  object
 18  Team1              102524 non-null  object
 19  Team2              102524 non-null  object
 20  total_run_y        102524 non-null  int64
 21  current_score      102524 non-null  int64
 22  wickets_left       102524 non-null  int64
 23  balls_left         102524 non-null  int64
 24  crr                102524 non-null  float64
 25  BowlingTeam        102524 non-null  object
 26  last_three         88363 non-null   float64
dtypes: float64(2), int64(13), object(12)
memory usage: 21.9+ MB

In [ ]:
# gathering the required cols for final df:
final_df = delivery_df[['BattingTeam', 'BowlingTeam', 'City', 'current_score', 'overs', 'wickets_left', 'crr','last_three', 'total_run_y']]

In [ ]:
final_df.head()

,BattingTeam,BowlingTeam,City,current_score,overs,wickets_left,crr,last_three,total_run_y
0,Rajasthan Royals,Gujarat Titans,Ahmedabad,0,0,10,0.0,NaN,130
1,Rajasthan Royals,Gujarat Titans,Ahmedabad,1,0,10,3.0,NaN,130
2,Rajasthan Royals,Gujarat Titans,Ahmedabad,2,0,10,4.0,NaN,130
3,Rajasthan Royals,Gujarat Titans,Ahmedabad,2,0,10,3.0,NaN,130
4,Rajasthan Royals,Gujarat Titans,Ahmedabad,2,0,10,2.4,NaN,130

In [ ]:
final_df.isnull().sum()

BattingTeam          0
BowlingTeam          0
City                 0
current_score        0
overs                0
wickets_left         0
crr                  0
last_three       14161
total_run_y          0
dtype: int64

In [ ]:
#removing 1st 3 overs data of every match which are NaN in our case:
final_df.dropna(inplace=True)

In [ ]:
#shuffling the df as we have sorted data:
final_df = final_df.sample(final_df.shape[0])

In [ ]:
final_df.shape

(88363, 9)

In [ ]:
final_df.head()

,BattingTeam,BowlingTeam,City,current_score,overs,wickets_left,crr,last_three,total_run_y
27464,Royal Challengers Bangalore,Chennai Super Kings,Dubai,99,14,8,6.750000,22.0,145
32541,Kolkata Knight Riders,Kings XI Punjab,Abu Dhabi,76,13,7,5.772152,15.0,164
87505,Kings XI Punjab,Kolkata Knight Riders,Chandigarh,91,14,6,6.275862,23.0,138
170608,Kings XI Punjab,Delhi Capitals,Chandigarh,64,8,6,7.111111,20.0,142
115893,Chennai Super Kings,Delhi Capitals,Abu Dhabi,116,15,7,7.483871,25.0,177

## Building the models:

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X = final_df.iloc[:,:-1]
Y = final_df.iloc[:,-1]

In [ ]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

In [ ]:
X_train.shape

(70690, 8)

In [ ]:
Y_train.shape

(70690,)

## Creating pipelines to tranform cols and train the model:

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [ ]:
# encoding batting team,bowling team and city:
step1 = ColumnTransformer(transformers=[
    ('ohe',OneHotEncoder(sparse=False,drop='first'),[0,1,2])
],remainder = 'passthrough')

## Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
#assigning our model to step 2 :
step2 = LinearRegression()

In [ ]:
#creating the pipeline:
pipe1 = Pipeline([
    ('step1',step1),
    ('step2',step2),
])

In [ ]:
#training the data with our pipeline:
pipe1.fit(X_train,Y_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe',
                                                  OneHotEncoder(drop='first',
                                                                sparse=False),
                                                  [0, 1, 2])])),
                ('step2', LinearRegression())])

In [ ]:
#testing the pipeline:
Y_pred1 = pipe1.predict(X_test)

In [ ]:
# evaluating the model:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import mean_squared_error,r2_score

In [ ]:
print('cvs:',cross_val_score(pipe1,X_train,Y_train,cv=5,scoring='r2').mean())
print('rmse:',mean_squared_error(Y_test,Y_pred1))

cvs: 0.5792974612172843
rmse: 368.8904038306707

## Decision Tree Regressor

In [ ]:
from sklearn.tree import DecisionTreeRegressor

In [ ]:
step2 = DecisionTreeRegressor(max_depth= 250,min_samples_split=2)

In [ ]:
#creating the pipeline:
pipe2 = Pipeline([
    ('step1',step1),
    ('step2',step2),
])

In [ ]:
#training the data with our pipeline:
pipe2.fit(X_train,Y_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe',
                                                  OneHotEncoder(drop='first',
                                                                sparse=False),
                                                  [0, 1, 2])])),
                ('step2', DecisionTreeRegressor(max_depth=250))])

In [ ]:
#testing the pipeline:
Y_pred2 = pipe2.predict(X_test)

In [ ]:
print('cvs:',cross_val_score(pipe2,X_train,Y_train,cv=5,scoring='r2').mean())
print('rmse:',mean_squared_error(Y_test,Y_pred2))

cvs: 0.830353183619728
rmse: 120.47807389803656

In [ ]:
#using randomized search cv for hyper parameter tuning:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
parameter = {
    'step2__max_depth' : [100,150,200,250,300],
    'step2__min_samples_split' : [2,3,4,5,6]
}

In [ ]:
rscv = RandomizedSearchCV(pipe2,param_distributions=parameter,cv=5,scoring='r2')

In [ ]:
rscv.fit(X_train,Y_train)

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('step1',
                                              ColumnTransformer(remainder='passthrough',
                                                                transformers=[('ohe',
                                                                               OneHotEncoder(drop='first',
                                                                                             sparse=False),
                                                                               [0,
                                                                                1,
                                                                                2])])),
                                             ('step2',
                                              DecisionTreeRegressor(max_depth=250))]),
                   param_distributions={'step2__max_depth': [100, 150, 200, 250,
                                                             300],
                                        'step2__min_samples_split': [2, 3, 4, 5,
                                                                     6]},
                   scoring='r2')

In [ ]:
rscv.best_score_

0.8340256299169105

In [ ]:
rscv.best_params_

{'step2__min_samples_split': 4, 'step2__max_depth': 200}

## Random Forest

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
step2 = RandomForestRegressor()

In [ ]:
#creating the pipeline:
pipe3 = Pipeline([
    ('step1',step1),
    ('step2',step2),
])

In [ ]:
#training the data with our pipeline:
pipe3.fit(X_train,Y_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe',
                                                  OneHotEncoder(drop='first',
                                                                sparse=False),
                                                  [0, 1, 2])])),
                ('step2', RandomForestRegressor())])

In [ ]:
#testing the pipeline:
Y_pred3 = pipe3.predict(X_test)

In [ ]:
adj_r2 = 1 - ((1-r2_score(Y_test,Y_pred3))*(X_test.shape[0]-1)/(X_test.shape[0]-X_test.shape[1]-1))
print('adj_r2:',adj_r2)
print('rmse:',mean_squared_error(Y_test,Y_pred3))

adj_r2: 0.934261334876154
rmse: 56.95178213187469

## XGBoost

In [ ]:
from xgboost import XGBRegressor

In [ ]:
step2 = XGBRegressor(n_estimators=400,max_depth=12,learning_rate=0.1)

In [ ]:
pipe3 = Pipeline([
    ('step1',step1),
    ('step2',step2),
])

In [ ]:
pipe3.fit(X_train,Y_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe',
                                                  OneHotEncoder(drop='first',
                                                                sparse=False),
                                                  [0, 1, 2])])),
                ('step2',
                 XGBRegressor(base_score=None, booster=None, callbacks=None,
                              colsample_bylevel=None, colsample_bynode=None,
                              colsample_bytree=None, early_stopping_rounds=None,
                              enable_categorical=False, eval_metric=None,
                              feature...None,
                              grow_policy=None, importance_type=None,
                              interaction_constraints=None, learning_rate=0.1,
                              max_bin=None, max_cat_threshold=None,
                              max_cat_to_onehot=None, max_delta_step=None,
                              max_depth=12, max_leaves=None,
                              min_child_weight=None, missing=nan,
                              monotone_constraints=None, n_estimators=400,
                              n_jobs=None, num_parallel_tree=None,
                              predictor=None, random_state=None, ...))])

In [ ]:
Y_pred3 = pipe3.predict(X_test)

In [ ]:
#print('cvs:',cross_val_score(pipe3,X_train,Y_train,cv=5,scoring='r2').mean())
adj_r2 = 1 - ((1-r2_score(Y_test,Y_pred3))*(X_test.shape[0]-1)/(X_test.shape[0]-X_test.shape[1]-1))
print('adj_r2:',adj_r2)
print('rmse:',mean_squared_error(Y_test,Y_pred3))

adj_r2: 0.9560838604359372
rmse: 38.04613932780118